package day7_test

import (
	"aoc2025/pkg/assert"
	"aoc2025/pkg/day7"
	"bufio"
	"strings"
	"testing"
)

func TestPart1(t *testing.T) {
	input := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`
	scanner := bufio.NewScanner(strings.NewReader(input))

	result, err := day7.Part1(scanner)

	assert.Nil(t, err)
	assert.Equal(t, "21", result)
}

func TestPart2(t *testing.T) {
	input := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`
	scanner := bufio.NewScanner(strings.NewReader(input))

	result, err := day7.Part2(scanner)

	assert.Nil(t, err)
	assert.Equal(t, "40", result)
}
